spring.application.name=oe-calc.multiplier

#Observability
management.endpoints.web.exposure.include=health,prometheus,info
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://oe-calc-opentelemetry-collector.dev.svc.cluster.local:4318/v1/traces
management.otlp.tracing.resource-attributes.service.name=${spring.application.name}
management.otlp.tracing.resource-attributes.deployment.environment=dev
management.tracing.propagation.type=W3C

#RabbitMQ
spring.rabbitmq.listener.simple.observe-enabled=true
spring.rabbitmq.cache.connection.mode=CONNECTION
spring.rabbitmq.cache.connection.size=5
spring.rabbitmq.cache.channel.size=25
spring.rabbitmq.cache.channel.checkout-timeout=5000
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=1000
spring.rabbitmq.template.retry.max-attempts=3
spring.rabbitmq.template.retry.multiplier=2.0
spring.rabbitmq.connection-timeout=10000
spring.rabbitmq.requested-heartbeat=30

#GRPC
spring.threads.virtual.enabled=true
grpc.server.keep-alive-time=30s
grpc.server.keep-alive-timeout=5s
grpc.server.permit-keep-alive-without-calls=true
grpc.server.max-inbound-message-size=4194304
