replicaCount: 2

image:
  repository: ghcr.io/arshwaseem/history-ms
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


database:
  host: postgres-history-rw
  port: 5432
  name: history
  secretName: postgres-history-app

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi