{
 "title": "Over Engineered Calculator",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Hikari Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HikariCP",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pool=\"HikariPool-1\"}",
     "legendFormat": "Active Db Connections - {{service}}"
    },
    {
     "expr": "hikaricp_connections_idle{pool=\"HikariPool-1\"}",
     "legendFormat": "Idle Connections {{service}}"
    },
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_sum[1m]) / rate(hikaricp_connections_acquire_seconds_count[1m])",
     "legendFormat": "Connection Time {{service}}"
    }
   ]
  },
  { "title": "Network I/O Webclient", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "WebClient Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_sum[1m])/rate(http_client_requests_seconds_count[1m])",
     "legendFormat": "Web Client Request Duration {{uri}}"
    }
   ]
  },
  {
   "title": "WebClient Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{status=~\"[45]..\"}[1m])) by (status)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WebClient Request Rate By Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Messages Published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(rabbitmq_published_total{service!=\"history-ms\"}[1m])",
     "legendFormat": "{{service}} : published"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_rejected_total[1m]))",
     "legendFormat": "Rate Of Rejected Messages"
    },
    {
     "expr": "sum(rate(rabbitmq_requeued_total[1m]))",
     "legendFormat": "Rate of Requeued Messages"
    }
   ]
  },
  {
   "title": "Messages Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "rate(rabbitmq_consumed_total{service=\"history-ms\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Process Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\".*actuator.*\"}[5m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=~\"adder-ms|api-gateway|auth|divider-ms|history-ms|multiplier-ms|subtractor-ms|user-ms\"}[5m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "100*(sum(rate(http_server_requests_seconds_count{status!~\"200|201\"}[1m])) by (service) / sum(rate(http_server_requests_seconds_count[1m])) by(service))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Cpu Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service)(process_cpu_usage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service,id)(jvm_memory_used_bytes{id=~\"G1 Eden Space|G1 Old Gen|G1 Survivor Space\",area=\"heap\"})",
     "legendFormat": "{{service}} : {{id}}"
    }
   ]
  }
 ]
}