spring.application.name=oe-calc.api-gateway

#Observability
management.endpoints.web.exposure.include=health,prometheus,info
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://oe-calc-opentelemetry-collector.dev.svc.cluster.local:4318/v1/traces
management.otlp.tracing.resource-attributes.service.name=${spring.application.name}
management.otlp.tracing.resource-attributes.deployment.environment=dev
management.tracing.propagation.type=W3C
spring.rabbitmq.listener.simple.observe-enabled=true

#Exclusions
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

#Tomcat
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.accept-count=100
server.tomcat.max-connections=10000
server.tomcat.connection-timeout=5000
server.tomcat.keep-alive-timeout=60000
server.tomcat.max-keep-alive-requests=100

#Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=true