apiVersion: v1
kind: Secret
metadata:
  name: {{ include "divider-ms.fullname" . }}-secret
  labels: {{- include "divider-ms.labels" . | nindent 4 }}
type: Opaque
stringData:
  rabbitmq-password: guest