apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-secret
  labels: {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: c80a6781f6ae1407704cc0221a857d666b7303139e65885f024745529b505595