apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  {{- if .Values.serviceConfig }}
  {{- if .Values.serviceConfig.sessionAffinity }}
  sessionAffinity: {{ .Values.serviceConfig.sessionAffinity }}
  {{- end }}
  {{- if .Values.serviceConfig.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.serviceConfig.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "auth.selectorLabels" . | nindent 4 }}