spring.application.name=oe-calc.subtractor
management.endpoints.web.exposure.include=health,prometheus,info
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://opentelemetry-collector.dev.svc.cluster.local:4318/v1/traces
management.otlp.tracing.resource-attributes.service.name=${spring.application.name}
management.otlp.tracing.resource-attributes.deployment.environment=dev
management.tracing.propagation.type=W3C
spring.rabbitmq.listener.simple.observe-enabled=true
